/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorPatientIdRouteImport } from './routes/doctor.patient.$id'

const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/doctor/settings',
  path: '/doctor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientIdRoute = DoctorPatientIdRouteImport.update({
  id: '/doctor/patient/$id',
  path: '/doctor/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/secretary': typeof SecretaryRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/secretary': typeof SecretaryRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctor': typeof DoctorIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/pending': typeof PendingRoute
  '/secretary': typeof SecretaryRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/doctor/': typeof DoctorIndexRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/pending'
    | '/secretary'
    | '/doctor/settings'
    | '/doctor/'
    | '/doctor/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/pending'
    | '/secretary'
    | '/doctor/settings'
    | '/doctor'
    | '/doctor/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/pending'
    | '/secretary'
    | '/doctor/settings'
    | '/doctor/'
    | '/doctor/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PendingRoute: typeof PendingRoute
  SecretaryRoute: typeof SecretaryRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorPatientIdRoute: typeof DoctorPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/doctor/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patient/$id': {
      id: '/doctor/patient/$id'
      path: '/doctor/patient/$id'
      fullPath: '/doctor/patient/$id'
      preLoaderRoute: typeof DoctorPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PendingRoute: PendingRoute,
  SecretaryRoute: SecretaryRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorPatientIdRoute: DoctorPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
